### ISSUE TITLE
Certificate officecdn.microsoft.com

### ISSUE THREAD

**Issue by jtsfvieira** [MSEndpointMgr/M365Apps#10]
**Describe the bug**
Is not a bug, but the SSL certificate of the page is expired.
officecdn.microsoft.com

**To Reproduce**
Try to tun the script as usual

**Expected behavior**
Download the file without issues

**Screenshots**
![image](https://github.com/MSEndpointMgr/M365Apps/assets/68940538/d1668a8b-be64-46e9-ab13-3e204bb7e641)
![image (1)](https://github.com/MSEndpointMgr/M365Apps/assets/68940538/7eacbc52-853c-428d-a7b3-8109394ccf84)

**Comment by jtsfvieira** [comment]
Solved now.
![image (2)](https://github.com/MSEndpointMgr/M365Apps/assets/68940538/89739b5a-7e9d-47db-8ad8-b73c003cf5eb)

**Comment by JankeSkanke** [comment]
Details here: 

https://x.com/jankeskanke/status/1806629702792028670?s=46
