### ISSUE TITLE
Error in doc

### ISSUE THREAD

**Issue by eichmeyer** [MSEndpointMgr/M365Apps#4]
In your doc you write:
powershell.exe -executionpolicy bypass -file Install-Proofing-Tools.ps1 -LanguageID nb-no -Action Install
powershell.exe -executionpolicy bypass -file Install-Proofing-Tools.ps1 -LanguageID nb-no -Action Uninstall
but the file is stored as:
InstallProofingTools.ps1

**Comment by JankeSkanke** [comment]
Will be fixed soon, just need to create new screenshots too. Thank you.

**Comment by JankeSkanke** [comment]
Docs updated
