### ISSUE TITLE
Evergreen URL for setup.exe

### ISSUE THREAD

**Issue by aaronparker** [MSEndpointMgr/M365Apps#5]
Rather than parse HTML, and download and extract the ODT as you're doing here: https://github.com/MSEndpointMgr/M365Apps/blob/233afbbbcdad72db8e6c0b1a33efc79d61bc26ef/M365AppsWin32App/InstallM365Apps.ps1#L124

You can instead use this evergreen URL which always points to the latest M365 Apps setup.exe: [https://officecdn.microsoft.com/pr/wsus/setup.exe](https://officecdn.microsoft.com/pr/wsus/setup.exe)

**Comment by JankeSkanke** [comment]
I know we looked into this in the early phases, and I dont remember why we decided to go down the ODT route. Will have a look.

**Comment by JankeSkanke** [comment]
Moved to evergreen url in version 1.2
