### ISSUE TITLE
User notification before closing Office apps

### ISSUE THREAD

**Issue by Kofl** [MSEndpointMgr/M365Apps#6]
Hi,

integration of ServiceUI would be great, so the user gets informed about closing the other office apps and saving their work, before e.g. Visio is installed.

Based on:
https://365bythijs.be/2019/09/19/installing-visio-onto-an-existing-office-installation-with-psadt-and-intune/

Thomas

**Comment by JankeSkanke** [comment]
It should be fairly easy for those who needs so to intergrate what we are doing here with PSADT and or using ServiceUI on their own. Will not be our focus for now at least.
